/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
}

dependencies {
    implementation("org.spigotmc:spigot-api:1.19-R0.1-SNAPSHOT")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.6.2")
}

group = "io.github.essentialsx"
version = "0.0.4-SNAPSHOT"
description = "An items.json generator for the EssentialsX FlatItemDb."
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
